# .travis.yml

language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t vatagin/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vatagin/docker-react npm run test
