FROM node:16-alpine

WORKDIR '/app'

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install -g npm@8.3.1
RUN npm install

COPY ./ ./

RUN chown -R node /app/node_modules
USER node

CMD ["npm", "start"]
